name: E2E-Upgrade-1.32

on:
  push:
    branches:
      - master
      - release-*
  pull_request: {}
  workflow_dispatch: {}

# Declare default permissions as read only.
permissions: read-all

env:
  # Common versions
  GO_VERSION: '1.23'
  KIND_VERSION: 'v0.22.0'
  KIND_IMAGE: 'kindest/node:v1.32.0'
  KIND_CLUSTER_NAME: 'ci-testing'

jobs:
  sandbox-upgrade:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          submodules: true
      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup Kind Cluster
        uses: helm/kind-action@ef37e7f390d99f746eb8b610417061a60e82a6cc # v1.14.0
        with:
          node_image: ${{ env.KIND_IMAGE }}
          cluster_name: ${{ env.KIND_CLUSTER_NAME }}
          config: ./test/kind-conf.yaml
          version: ${{ env.KIND_VERSION }}
      - name: Build image
        run: |
          export IMAGE="agent-sandbox-controller:latest"
          docker build -f dockerfiles/agent-sandbox-controller.Dockerfile  --pull --no-cache . -t $IMAGE
          kind load docker-image --name=${KIND_CLUSTER_NAME} $IMAGE || { echo >&2 "kind not installed or error loading image: $IMAGE"; exit 1; }
      - name: Install Kruise Agents
        run: |
          CONTROLLER_IMG=agent-sandbox-controller:latest make deploy-agent-sandbox-controller
          bash hack/wait-agent-sandbox-controller.sh
      - name: Run E2E Tests
        run: |
          export KUBECONFIG=/home/runner/.kube/config
          hack/run-agents-e2e-test.sh --print-info --focus 'Sandbox Upgrade Lifecycle|SandboxUpdateOps E2E'
